export const data = {
  products: [
    {
      id: 1,
      name: "Hoodie Cupid - Men's",
      categories: ["hoodies", "men"],
      description: "Men's hoodie with a cupid design.",
      price: 34.99,
      image: "/data/men-hoodie-1.jpg",
      newProducts: true,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 2,
      name: "Hoodie White - Men's",
      categories: ["hoodies", "men"],
      description: "Men's hoodie with a white design.",
      price: 19.99,
      image: "/data/men-hoodie-2.jpg",
      newProducts: true,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 3,
      name: "Hoodie Gray - Men's",
      categories: ["hoodies", "men"],
      description: "Men's hoodie with a gray design.",
      price: 9.99,
      image: "/data/men-hoodie-3.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 4,
      name: "Hoodie Black - Men's",
      categories: ["hoodies", "men"],
      description: "Men's hoodie with a black design.",
      price: 59.99,
      image: "/data/men-hoodie-4.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 5,
      name: "Hoodie Posadera - Men's",
      categories: ["hoodies", "men"],
      description: "Men's hoodie with a posadera design.",
      price: 89.99,
      image: "/data/men-hoodie-5.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 6,
      name: "Pant Black - Men's",
      categories: ["pants", "men"],
      description: "Men's pant with a black design.",
      price: 69.99,
      image: "/data/men-pant-1.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 7,
      name: "Pant White - Men's",
      categories: ["pants", "men"],
      description: "Men's pant with a white design.",
      price: 39.99,
      image: "/data/men-pant-2.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 8,
      name: "Pant Gray - Men's",
      categories: ["pants", "men"],
      description: "Men's pant with a gray design.",
      price: 79.99,
      image: "/data/men-pant-3.jpg",
      newProducts: true,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 9,
      name: "Pant Blue - Men's",
      categories: ["pants", "men"],
      description: "Men's pant with a blue design.",
      price: 29.99,
      image: "/data/men-pant-4.jpg",
      newProducts: true,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 10,
      name: "Shirt Black - Men's",
      categories: ["shirts", "men"],
      description: "Men's shirt with a black design.",
      price: 19.99,
      image: "/data/men-shirt-1.jpg",
      newProducts: false,
      mostSold: true,
      quantity: 0,
    },
    {
      id: 11,
      name: "Shirt Neighbors - Men's",
      categories: ["shirts", "men"],
      description: "Men's shirt with a neighbors design.",
      price: 9.99,
      image: "/data/men-shirt-2.jpg",
      newProducts: false,
      mostSold: true,
      quantity: 0,
    },
    {
      id: 12,
      name: "Shirt Gray - Men's",
      categories: ["shirts", "men"],
      description: "Men's shirt with a gray design.",
      price: 49.99,
      image: "/data/men-shirt-3.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 13,
      name: "Hoodie Evil - Women's",
      categories: ["hoodies", "women"],
      description: "Women's hoodie with an evil design.",
      price: 69.99,
      image: "/data/women-hoodie-1.jpg",
      newProducts: true,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 14,
      name: "Hoodie Boston - Women's",
      categories: ["hoodies", "women"],
      description: "Women's hoodie with a boston design.",
      price: 99.99,
      image: "/data/women-hoodie-2.jpg",
      newProducts: false,
      mostSold: true,
      quantity: 0,
    },
    {
      id: 15,
      name: "Hoodie White - Women's",
      categories: ["hoodies", "women"],
      description: "Women's hoodie with a white design.",
      price: 59.99,
      image: "/data/women-hoodie-3.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 16,
      name: "Hoodie Dallas - Women's",
      categories: ["hoodies", "women"],
      description: "Women's hoodie with a dallas design.",
      price: 39.99,
      image: "/data/women-hoodie-4.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 17,
      name: "Hoodie Gray - Women's",
      categories: ["hoodies", "women"],
      description: "Women's hoodie with a gray design.",
      price: 79.99,
      image: "/data/women-hoodie-5.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 18,
      name: "Pant Black - Women's",
      categories: ["pants", "women"],
      description: "Women's pant with a black design.",
      price: 69.99,
      image: "/data/women-pant-1.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 19,
      name: "Pant Blue - Women's",
      categories: ["pants", "women"],
      description: "Women's pant with a blue design.",
      price: 29.99,
      image: "/data/women-pant-2.jpg",
      newProducts: false,
      mostSold: true,
      quantity: 0,
    },
    {
      id: 20,
      name: "Pant Light Blue - Women's",
      categories: ["pants", "women"],
      description: "Women's pant with a light blue design.",
      price: 19.99,
      image: "/data/women-pant-3.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 21,
      name: "Pant Dark Blue - Women's",
      categories: ["pants", "women"],
      description: "Women's pant with a dark blue design.",
      price: 89.99,
      image: "/data/women-pant-4.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 22,
      name: "Shirt Boston - Women's",
      categories: ["shirts", "women"],
      description: "Women's shirt with a boston design.",
      price: 99.99,
      image: "/data/women-shirt-1.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 23,
      name: "Shirt Evil - Women's",
      categories: ["shirts", "women"],
      description: "Women's shirt with an evil design.",
      price: 49.99,
      image: "/data/women-shirt-2.jpg",
      newProducts: false,
      mostSold: true,
      quantity: 0,
    },
    {
      id: 24,
      name: "Shirt Black - Women's",
      categories: ["shirts", "women"],
      description: "Women's shirt with a black design.",
      price: 39.99,
      image: "/data/women-shirt-3.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
    {
      id: 25,
      name: "Shirt Red - Women's",
      categories: ["shirts", "women"],
      description: "Women's shirt with a red design.",
      price: 59.99,
      image: "/data/women-shirt-4.jpg",
      newProducts: false,
      mostSold: false,
      quantity: 0,
    },
  ],
  users: [],
  orders: [],
};
